storageClasses:
  default:
    name: standard
  shared:
    name: standard

ingress:
  enabled: true
  host: gerrit.jarvis.local
  additionalAnnotations:
    cert-manager.io/cluster-issuer: jarvis-ca-issuer
  tls:
    enabled: true
    secret:
      create: false
      name: gerrit-tls

gerrit:
  plugins:
    packaged:
      - commit-message-length-validator
      - download-commands
      - replication
      - reviewnotes
      - webhooks
      - delete-project
      - gitiles
  service:
    ssh:
      enabled: true
      port: 29418

  etc:
    # Some values are expected to have a specific value for the deployment installed
    # by this chart to work. These are marked with `# FIXED`.
    # Do not change them!
    config:
      gerrit.config: |-
        [gerrit]
          basePath = git # FIXED
          serverId = gerrit-1
          # The canonical web URL has to be set to the Ingress host, if an Ingress
          # is used. If a LoadBalancer-service is used, this should be set to the
          # LoadBalancer's external IP. This can only be done manually after installing
          # the chart, when you know the external IP the LoadBalancer got from the
          # cluster.
          canonicalWebUrl = http://gerrit.jarvis.local/
          disableReverseDnsLookup = true
        [index]
          type = LUCENE
          onlineUpgrade = false # FIXED
        [auth]
          type = LDAP
          gitBasicAuthPolicy = LDAP
        [ldap]
          server = ldap://ldap-openldap.ldap.svc.cluster.local
          username = cn=readonly,dc=jarvis,dc=local
          password = readonly
          accountBase = ou=Users,dc=jarvis,dc=local
          accountPattern = (&(objectClass=inetOrgPerson)(uid=${username}))
          accountFullName = ${cn}
          accountScope = sub
          groupBase = ou=Groups,dc=jarvis,dc=local
          groupScope = sub
          groupPattern = (&(objectClass=groupOfUniqueNames)(cn=${groupname}))
          groupMemberPattern = (&(objectClass=groupOfUniqueNames)(uniqueMember=${dn}))
          localUsernameToLowerCase = true
        [httpd]
          # If using an ingress use proxy-http or proxy-https
          listenUrl = proxy-http://*:8080/
          requestLog = true
        [sshd]
          listenAddress = *:29418
        [transfer]
          timeout = 120 s
        [user]
          name = Gerrit Code Review
          email = gerrit@example.com
          anonymousCoward = Unnamed User
        [cache]
          directory = cache
        [container]
          user = gerrit # FIXED
          javaHome = /usr/lib/jvm/java-11-openjdk # FIXED
          javaOptions = -Djavax.net.ssl.trustStore=/var/gerrit/etc/keystore # FIXED
          javaOptions = -Xms200m
          # Has to be lower than 'gerrit.resources.limits.memory'. Also
          # consider memories used by other applications in the container.
          javaOptions = -Xmx4g
      replication.config: |-
        [gerrit]
          autoReload = false
          replicateOnStartup = true
          defaultForceUpdate = true
        # [remote "replica"]
        # url = http://gerrit-replica.example.com/git/${name}.git
        # replicationDelay = 0
        # timeout = 30
