#Remove any resources deployed
- set_fact:
    _async: "{{ chart_async | default(600) }}"
    _delay: "{{ chart_check_status_delay | default(5) }}"
    remove_artifacts: "{{ remove_artifacts }}"
    environment_name: "{{ environment_name }}"

- name: Cleanup Task
  when: remove_artifacts == "true" and environment_name == "development"
  block:
    - name: Delete Helm Release
      shell: helm delete --kubeconfig="{{ cluster_kubeconfig_path }}/kubeconfig" "{{ chart.release_name }}" -n "{{ chart.remote_namespace }}"
      loop: "{{ charts }}"
      loop_control:
        loop_var: "chart"
      async: "{{ _async }}"
      poll: 0
      register: cleanup_async_results

    - name: Wait for helm delete results
      vars:
        async_results: "{{ cleanup_async_results }}"
      include_tasks: ./roles/common/tasks/check_sync_status.yaml
  become: true
