apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-flow
data:
  cluster.json: |
    {
     "namespace": "{{ $.Values.namespace }}",
     "use_existing_cluster": "true"
    }
  image.json: |
    {
     "build_from_source": true,
     "image_from": "harbor-core.jarvis.local/library/ubuntu:focal",
     "image_name": "udr",
     "project": "udr",
     "repo": "udr",
     "tag": "1.built",
     "image_fullname": "cnf/udr:1.0",
     "path": "images/udr",
     "namespace": "{{ $.Values.namespace }}",
     "build": {
        "git_repo": "{{ $.Values.git_repo }}",
        "target_loc": "/src/checkout/udr",
        "refspec": "{{ $.Values.refspec }}",
        "version": "refs/changes/*:refs/changes/*"
     }
    }
  chart.json: |
    {
      "chart_name": "udr",
      "project": "udr",
      "repo": "udr",
      "version": "0.1.0",
      "build_from_source": true,
      "path": "charts",
      "namespace": "{{ $.Values.namespace }}",
      "build": {
        "git_repo": "{{ $.Values.git_repo }}",
        "target_loc": "/src/checkout/udr",
        "refspec": "{{ $.Values.refspec }}",
        "version": "refs/changes/*:refs/changes/*"
      },
      "release_name": "udr",
      "images": {
        "applications": {
          "udr": {
            "tag": "1.0",
            "name": "udr",
            "repo": "udr"
          }
        }
      }
    }
  default.json: |
    {
      "proxy": {
        "http": "",
        "https": "",
        "noproxy": "",
        "enabled": false
      },
      "docker_content_trust": {
        "DOCKER_CONTENT_TRUST": 1,
        "DOCKER_CONTENT_TRUST_SERVER": "https://harbor-notary.jarvis.local",
        "DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE": "passphrase",
        "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE": "passphrase"
      },
      "chart_registry_url": "harbor-core.jarvis.local/chartrepo",
      "chart_repository": "jarvis-harbor",
      "docker_registry": "harbor-core.jarvis.local",
      "harbor_secret_mounted_path": "/workspace/helm-creds",
      "harbor_secret_pull_mounted_path": "/workspace/helm-creds/pull",
      "harbor_secret_push_mounted_path": "/workspace/helm-creds/push",
      "clone_async_batch_size": 20,
      "chart_async_batch_size": 20,
      "image_async_batch_size": 2
    }
  cleanup.json: |
    {
     "remove_artifacts": "true"
    }
