# Default values for project-aio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  applications:
    project:
      tag: latest
      name: attcomdev/jarvis-connector
      repo: quay.io
  pull:
    policy: Always

node_labels:
  project:
    key: kubernetes.io/os
    value: linux

over_rides: {}

params:
  gerrit:
    user: ""
    password: ""
    ssh_key: ""
    host: gerrit.jarvis.local
    ldap_group_cn: ""
  harbor:
    host: harbor-core.jarvis.local
    member_ldap_dn:
      project: ""
      staging: ""
  endpoints:
    hostname: localhost
    tls:
      cert_manager: true
      issuer:
        name: jarvis-ca-issuer
        kind: ClusterIssuer

config:
  ci:
    verify: true
  test:
    ldap_username: jarvis
    ldap_password: password
