#Build docker image using Makefile given git repository location to clone code from
- set_fact:
    _async: "{{ git_async | default(600) }}"
    _delay: "{{ git_check_status_delay | default(3) }}"

- name: Run async git clone
  shell: |
    if [ -n "{{ repo.build.user | default("", true) }}" ] && [ -n "{{ repo.build.password | default("", true) }}" ]; then \
      git config --global credential.username {{ repo.build.user }} && git config --global credential.helper "!echo password={{ repo.build.password }}; echo"; \
    fi
    git clone {{ repo.build.git_repo }} {{ repo.build.target_loc }};
    cd {{ repo.build.target_loc }};
    git pull {{ repo.build.git_repo }} {{ repo.build.refspec }};
  async: "{{ _async }}"
  poll: 0
  loop: "{{ repos }}"
  loop_control:
    loop_var: "repo"
  register: git_async_results
  when:
    - stage == "clone"

- name: Wait for git clone results
  vars:
    async_results: "{{ git_async_results }}"
  include_tasks: ./roles/common/tasks/check_sync_status.yaml
  when:
    - stage == "clone"
