apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-flow
data:
  cluster.json: |
    {
     "namespace": "{{ $.Values.namespace }}",
     "use_existing_cluster": "true"
    }
  image.json: |
    [
      {
       "image_from": "harbor-core.jarvis.local/library/ubuntu:focal",
       "build_from_source": true,
       "image_name": "amf",
       "project": "amf",
       "repo": "amf",
       "image_fullname": "amf/amf:1.0",
       "path": "images/amf",
       "namespace": "{{ $.Values.namespace }}",
       "build": {
          "git_repo": "{{ $.Values.git_repo }}",
          "target_loc": "/src/checkout/amf",
          "refspec": "{{ $.Values.refspec }}",
          "version": "refs/changes/*:refs/changes/*"
       }
      }
    ]
  chart.json: |
    [
      {
        "chart_name": "amf",
        "project": "amf",
        "repo": "amf",
        "version": "0.1.0",
        "build_from_source": true,
        "path": "charts",
        "build": {
          "git_repo": "{{ $.Values.git_repo }}",
          "target_loc": "/src/checkout/amf",
          "refspec": "{{ $.Values.refspec }}",
          "version": "refs/changes/*:refs/changes/*"
        },
        "namespace": "{{ $.Values.namespace }}",
        "release_name": "amf",
        "images": {
          "applications": {
            "amf": {
              "tag": "1.0",
              "name": "amf",
              "repo": "amf"
            }
          }
        }
      }
    ]
  default.json: |
    {
      "proxy": {
        "http": "",
        "https": "",
        "noproxy": "",
        "enabled": false
      },
      "docker_content_trust": {
        "DOCKER_CONTENT_TRUST": 1,
        "DOCKER_CONTENT_TRUST_SERVER": "https://harbor-notary.jarvis.local",
        "DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE": "passphrase",
        "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE": "passphrase"
      },
      "chart_registry_url": "harbor-core.jarvis.local/chartrepo",
      "chart_repository": "jarvis-harbor",
      "docker_registry": "harbor-core.jarvis.local",
      "harbor_secret_mounted_path": "/workspace/helm-creds",
      "clone_async_batch_size": 20,
      "chart_async_batch_size": 20,
      "image_async_batch_size": 2
    }
  cleanup.json: |
    {
     "remove_artifacts": "true"
    }
