apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-flow
data:
  cluster.json: |
    {
     "use_existing_cluster": "true"
    }
  image.json: |
    [
      {
       "image_from": "harbor-core.jarvis.local/library/ubuntu:focal",
       "build_from_source": false,
       "image_name": "mongodb-sharded",
       "project": "mongodb",
       "repo": "mongodb-sharded",
       "tag": "4.4.3",
       "image_fullname": "mongodb/mongodb-sharded:4.4.3",
       "path": "",
       "build": {
          "git_repo": "docker.io/bitnami/mongodb-sharded",
          "tag": "4.4.3-debian-10-r44"
       }
      }
    ]
  chart.json: |
    [{
      "chart_name": "mongodb-sharded",
      "project": "mongodb",
      "repo": "mongodb-sharded",
      "version": "3.3.3",
      "build_from_source": false,
      "path": "",
      "build": {
        "name": "https://charts.bitnami.com/bitnami",
        "local_repo": "bitnami_mongodb",
        "target_loc": "/src/fetch/charts"
      },
      "namespace": "{{ $.Values.namespace }}",
      "release_name": "mongodb-bitnami",
      "sources": {
        "image_map": {
          "tag": ["releases", "image", "tag"],
          "tmp_name": ["releases", "image", "repository"],
          "tmp_repo": ["releases", "image", "registry"]
        }
      },
      "releases": {
        "image": {
          "registry": "docker.io",
          "repository": "bitnami/mongodb-sharded",
          "tag": "4.4.4-debian-10-r28"
        }
      }
    }]
  default.json: |
    {
      "proxy": {
        "http": "",
        "https": "",
        "noproxy": "",
        "enabled": false
      },
      "docker_content_trust": {
        "DOCKER_CONTENT_TRUST": 1,
        "DOCKER_CONTENT_TRUST_SERVER": "https://harbor-notary.jarvis.local",
        "DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE": "passphrase",
        "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE": "passphrase"
      },
      "chart_registry_url": "harbor-core.jarvis.local/chartrepo",
      "chart_repository": "jarvis-harbor",
      "docker_registry": "harbor-core.jarvis.local",
      "harbor_secret_mounted_path": "/workspace/helm-creds",
      "harbor_secret_pull_mounted_path": "/workspace/helm-creds/pull",
      "harbor_secret_push_mounted_path": "/workspace/helm-creds/push",
      "clone_async_batch_size": 20,
      "chart_async_batch_size": 20,
      "image_async_batch_size": 2
    }
  cleanup.json: |
    {
     "remove_artifacts": "true"
    }
