{{- define "role-triggers_admin" -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{- include "helpers.labels.labels" (dict "Global" $ "PartOf" "tekton-triggers") | nindent 4 }}
  name: tekton-triggers-admin
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - tekton-triggers
    verbs:
      - use
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "role-triggers_admin" ) }}
