{{- define "secret-triggers" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: triggers-webhook-certs
  labels: {{- include "helpers.labels.labels" (dict "Global" $ "Component" "webhook" "PartOf" "tekton-triggers") | nindent 4 }}
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "secret-triggers" ) }}
