{{- define "configmap-artifact-bucket" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-artifact-bucket
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "helpers.labels.labels" (dict "Global" $) | nindent 4 }}
data:
{{- if $.Values.controller.conf.artifact_bucket.location }}
  # location of the gcs bucket to be used for artifact storage
  # location: "gs://bucket-name"
  location: {{ $.Values.controller.conf.artifact_bucket.location | quote }}
{{- end }}

{{- if $.Values.controller.conf.artifact_bucket.bucket.service.account.secret.name }}
  # name of the secret that will contain the credentials for the service account
  # with access to the bucket
  # bucket.service.account.secret.name:
  bucket.service.account.secret.name: {{ $.Values.controller.conf.artifact_bucket.bucket.service.account.secret.name | quote }}
{{- end}}

{{- if $.Values.controller.conf.artifact_bucket.bucket.service.account.secret.key }}
  # The key in the secret with the required service account json
  # bucket.service.account.secret.key:
  bucket.service.account.secret.key: {{ $.Values.controller.conf.artifact_bucket.bucket.service.account.secret.key | quote }}
{{- end}}

{{- if $.Values.controller.conf.artifact_bucket.bucket.service.account.field.name }}
  # The field name that should be used for the service account
  # Valid values: GOOGLE_APPLICATION_CREDENTIALS, BOTO_CONFIG.
  # bucket.service.account.field.name: GOOGLE_APPLICATION_CREDENTIALS
  bucket.service.account.field.name: {{ $.Values.controller.conf.artifact_bucket.bucket.service.account.field.name | quote }}
{{- end }}
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "configmap-artifact-bucket" ) }}
