{{- define "mutatingwebhookconfiguration-webhook" -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.pipeline.tekton.dev
  labels: {{- include "helpers.labels.labels" (dict "Global" $ "Component" "webhook" "PartOf" "tekton-pipelines") | nindent 4 }}
webhooks:
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: tekton-pipelines-webhook
      namespace: {{ $.Release.Namespace }}
  failurePolicy: Fail
  sideEffects: None
  name: webhook.pipeline.tekton.dev
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "mutatingwebhookconfiguration-webhook" ) }}
