---
- hosts: localhost
  tasks:
    - name: Get list of objects
      shell: "jq -c '.[]' {{ loop_source }}"
      register: data

    - set_fact:
        async_batch_size: 2
        stage: "default"

    - name: Get list of internal staging repos
      when: ( stage == "promote_chart")
      shell: "jq -c '.[] | {repo: (\"https://{{ chart_registry_url }}/\"+.project+\"-staging\"), secret: \"{{ harbor_secret_pull_mounted_path }}\", name:  (.project+\"-staging\")}'  {{ loop_source }}  | sort | uniq"
      register: staging_internal_repos

    - name: Get list of internal stable repos
      when: ( stage == "promote_chart")
      shell: "jq -c '.[] | {repo: (\"https://{{ chart_registry_url }}/\"+.project), secret: \"{{ harbor_secret_push_mounted_path }}\", name: .project}'  {{ loop_source }}  | sort | uniq"
      register: internal_repos

    - include_tasks: ./roles/charts/tasks/setup_helm_repo.yaml
      when: ( stage == "promote_chart")
      loop: "{{ staging_internal_repos.stdout_lines + internal_repos.stdout_lines}}"
      vars:
        repo: "{{ item }}"

    - include_tasks: ./roles/promote/tasks/main.yaml
      when: data.stdout_lines |length > 0
      loop: "{{ data.stdout_lines | map('from_json') | batch(async_batch_size) | list }}"
      loop_control:
        loop_var: "items"
