# Default values for dex-aio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  applications:
    connector:
      tag: latest
      name: attcomdev/jarvis-connector
      repo: quay.io
    task_git:
      tag: v0.18.1
      name: tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
      repo: gcr.io
    task_create_namespace:
      tag: "1.0"
      name: standard-container
      repo: docker.io
    task_secrets:
      tag: "1.0"
      name: standard-container
      repo: docker.io
    task_results:
      tag: "1.0"
      name: standard-container
      repo: docker.io
    task_curl:
      tag: "3.8"
      name: evl.ms/curl
      repo: quay.io
  pull:
    policy: Always

node_labels:
  connector:
    key: kubernetes.io/os
    value: linux

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  internal_certs_dir:

over_rides: {}

params:
  gerrit:
    user: jarvis
    password: password
    host: gerrit.jarvis.local
  tekton:
    dashboard:
      host: tekton.jarvis.local
  endpoints:
    hostname: el-jarvis-system.jarvis-system.svc.cluster.local
    tls:
      cert_manager: true
      issuer:
        name: jarvis-ca-issuer
        kind: ClusterIssuer
  grafana:
    dashboard:
      host: grafana.jarvis.local
      title: loki-pipeline-logs-dashboard
      uid: lokiPipelineDash
      orgid: 1
  harbor:
    dashboard:
      host: harbor-core.jarvis.local