{{- define "Pipeline-merge" -}}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ template "helpers.labels.fullname" . }}-merge
spec:
  params:
    - name: repoRoot
    - name: project
    - name: changeNumber
    - name: patchSetNumber
    - name: checkerUUID
  workspaces:
    - name: output
  tasks:
    - name: createprojectaccess
      taskRef:
        name: {{ template "helpers.labels.fullname" . }}-createprojectaccess
      params:
        - name: repoRoot
          value: $(params.repoRoot)
        - name: project
          value: $(params.project)
        - name: changeNumber
          value: $(params.changeNumber)
        - name: patchSetNumber
          value: $(params.patchSetNumber)
        - name: pipeline
          value: "merge"
      workspaces:
        - name: output
          workspace: output
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Pipeline-merge" ) }}