apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: development-pipeline
  namespace: {{ $.Release.Namespace }}
spec:
  params:
    - name: pipeline
  workspaces:
    - name: k8s_cluster_data
    - name: development_pipeline_data
  tasks:
    - name: microflow-setup-cluster-config
      taskRef:
        name: setup-cluster-config
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data

    - name: microflow-setup-image-config
      taskRef:
        name: setup-image-config
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data

    - name: microflow-setup-chart-config
      taskRef:
        name: setup-chart-config
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data

    - name: microflow-setup-cleanup-config
      taskRef:
        name: setup-cleanup-config
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data

    - name: microflow-k8s
      runAfter:
        - microflow-setup-cluster-config
      taskRef:
        name: k8s-cluster
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data

    - name: microflow-images
      runAfter:
        - microflow-setup-cluster-config
        - microflow-setup-image-config
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data
      taskRef:
        name: image-tasks

    - name: microflow-charts
      runAfter:
        - microflow-setup-cluster-config
        - microflow-setup-chart-config
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data
      taskRef:
        name: chart-tasks

    - name: microflow-deployment-manifests
      runAfter:
        - microflow-setup-image-config
        - microflow-setup-chart-config
        - microflow-setup-cluster-config
        - microflow-setup-cleanup-config
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data
      taskRef:
        name: deployment-manifests

    - name: microflow-functional
      runAfter:
        - microflow-deployment-manifests
        - microflow-k8s
        - microflow-images
        - microflow-charts
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data
      taskRef:
        name: functional

    - name: microflow-promote-artifacts
      when:
        - input: $(params.pipeline)
          operator: in
          values: ["merge"]
      runAfter:
        - microflow-functional
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data
      taskRef:
        name: promote
  finally:
    - name: microflow-cleanup
      workspaces:
        - name: k8s_cluster_data
          workspace: k8s_cluster_data
        - name: development_pipeline_data
          workspace: development_pipeline_data
      taskRef:
        name: cleanup
